# Generated by Django 4.2.6 on 2024-05-24 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='PhoneNumbe',
            new_name='PhoneNumber',
        ),
    ]
