# Generated by Django 4.2.6 on 2024-05-19 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_delete_userpersonalinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
