# Generated by Django 4.2.6 on 2024-05-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userpersonalinfo_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='chronic_diseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='injuries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='surgeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='lifestyleinfo',
            name='alcohol',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lifestyleinfo',
            name='exercise',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lifestyleinfo',
            name='smoking',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpersonalinfo',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userpersonalinfo',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpersonalinfo',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpersonalinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpersonalinfo',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='userpersonalinfo',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.RemoveField(
            model_name='usermedicalinfo',
            name='allergies',
        ),
        migrations.AddField(
            model_name='lifestyleinfo',
            name='occupation',
            field=models.ManyToManyField(blank=True, to='accounts.occupation'),
        ),
        migrations.AddField(
            model_name='usermedicalinfo',
            name='chronic_diseases',
            field=models.ManyToManyField(blank=True, to='accounts.chronic_diseases'),
        ),
        migrations.AddField(
            model_name='usermedicalinfo',
            name='current_medication',
            field=models.ManyToManyField(blank=True, related_name='current_medication', to='accounts.medication'),
        ),
        migrations.AddField(
            model_name='usermedicalinfo',
            name='injuries',
            field=models.ManyToManyField(blank=True, to='accounts.injuries'),
        ),
        migrations.AddField(
            model_name='usermedicalinfo',
            name='past_medication',
            field=models.ManyToManyField(blank=True, related_name='past_medication', to='accounts.medication'),
        ),
        migrations.AddField(
            model_name='usermedicalinfo',
            name='surgeries',
            field=models.ManyToManyField(blank=True, to='accounts.surgeries'),
        ),
        migrations.AddField(
            model_name='usermedicalinfo',
            name='allergies',
            field=models.ManyToManyField(blank=True, to='accounts.allergy'),
        ),
    ]
