# Generated by Django 4.2.6 on 2024-05-23 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_allergy_chronic_diseases_injuries_medication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpersonalinfo',
            name='full_name',
        ),
    ]
