# Generated by Django 4.2.6 on 2024-05-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_userpersonalinfo_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonalinfo',
            name='public_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
