# Generated by Django 4.2.6 on 2024-05-23 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userpersonalinfo_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifestyleinfo',
            name='occupation',
        ),
        migrations.AddField(
            model_name='lifestyleinfo',
            name='occupation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.occupation'),
        ),
    ]
