# Generated by Django 4.2.6 on 2024-05-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_card_files_wallet_card_files_card_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='wallets', to='accounts.card'),
        ),
    ]
