# Generated by Django 4.2.6 on 2024-05-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_lifestyleinfo_occupation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonalinfo',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
