# Generated by Django 4.2.6 on 2024-05-25 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_card_date_alter_wallet_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopital_admin',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitals'),
        ),
        migrations.AlterField(
            model_name='hopital_admin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
